music_service/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import *


urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('register_client/', views.register_client, name='register_client'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),

    path('add_playlist/', Playlist_CreateView.as_view(), name='add_playlist'),
    path('delete_playlist/', DeletePlaylistView.as_view(), name='delete_playlist'),
    path('playlists/', Playlists_ListView.as_view(), name='playlists'),
    path('playlist_songs/<int:playlist_id>/', Playlist_Song.as_view(), name='playlist_songs'),

    path('add_song/', Song_CreateView.as_view(), name='add_song'),
    path('delete_song/', DeleteSongsView.as_view(), name='delete_song'),
    path('song_list/', Song_ListView.as_view(), name='song_list'),

    path('key/', Key_ListView.as_view(), name='key'),
    path('key/get_key/', views.get_key, name='get_key'),
    path('bmp/', BPM_ListView.as_view(), name='bpm'),
    path('key/get_bpm/', views.get_bpm, name='get_bpm')
  ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music_service/music_service/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music_service/main/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator


class Song(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='songs')
    title = models.CharField(max_length=20)
    audio_file = models.FileField(upload_to='audio/', validators=[FileExtensionValidator(['mp3', 'wav'])])
    image = models.ImageField(upload_to='images/', validators=[FileExtensionValidator(['jpg', 'png'])])

    def __str__(self):
        return self.title

@receiver(post_delete, sender=Song)
def delete_song_files(sender, instance, **kwargs):
    instance.audio_file.delete(False)
    instance.image.delete(False)


class Playlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='playlists')
    title = models.CharField(max_length=20)
    songs = models.ManyToManyField('Song', related_name='playlists')
    image = models.ImageField(upload_to='images/', validators=[FileExtensionValidator(['jpg', 'png'])])

    def __str__(self):
        return self.title

@receiver(post_delete, sender=Playlist)
def delete_song_files(sender, instance, **kwargs):
    instance.image.delete(False)

music_service/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Song, Playlist, User


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(label='username')
    password = forms.CharField(label='password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username already exists')
        return username


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'TextInput'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'class': 'TextInput'}))


class SongForm(forms.ModelForm):
    playlist = forms.ModelChoiceField(queryset=Playlist.objects.none(), empty_label=None, required=True)

    class Meta:
        model = Song
        fields = ['title', 'audio_file', 'image']
        widgets = {
            'image': forms.ClearableFileInput(attrs={'required': True}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['playlist'].queryset = Playlist.objects.filter(user=user)


class PlaylistForm(forms.ModelForm):

    class Meta:
        model = Playlist
        fields = ['title', 'image']

    widgets = {
        'image': forms.ClearableFileInput(attrs={'required': True}),
    }


class DeleteSongForm(forms.Form):
    songs = forms.ModelMultipleChoiceField(queryset=None, widget=forms.CheckboxSelectMultiple)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['songs'].queryset = Song.objects.filter(user=user)
        self.fields['songs'].empty_label = None


class DeletePlaylistForm(forms.Form):
    playlist = forms.ModelMultipleChoiceField(queryset=None, widget=forms.CheckboxSelectMultiple)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['playlist'].queryset = Playlist.objects.filter(user=user)
        self.fields['playlist'].empty_label = None

music_service/main/views.py
import http.client
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, CreateView, DeleteView, TemplateView, DetailView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView, LogoutView
from .forms import *
from .models import *
from .utils.Detector import *
from django.core import serializers
from django.http import JsonResponse
import json


class HomeView(TemplateView):
    template_name = 'main/home.html'


def register_client(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            User.objects.create_user(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            return redirect('home')
        else:
            return redirect('register_client')

    else:
        form = UserRegistrationForm()
    return render(request, 'main/register.html', {'form': form})


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'main/login.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(self.request, username=username, password=password)

        if user is not None:
            login(self.request, user)
            return redirect('home')
        else:
            return self.form_invalid(form)


class CustomLogoutView(LogoutView):
    template_name = 'main/home.html'


class Playlists_ListView(ListView):
    template_name = 'main/playlists.html'
    context_object_name = 'playlists'

    def dispatch(self, request, *args, **kwargs): 
        if not request.user.is_authenticated:
            return redirect('register_client')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):   
        playlists_ = Playlist.objects.filter(user_id=self.request.user.id)
        return playlists_


class Playlist_CreateView(CreateView):
    model = Playlist
    template_name = 'main/add_playlist.html'
    form_class = PlaylistForm
    success_url = reverse_lazy('playlists')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('register_client')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class DeletePlaylistView(FormView):
    template_name = 'main/delete_playlist.html'
    form_class = DeletePlaylistForm
    success_url = reverse_lazy('playlists')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('register_client')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        playlists = form.cleaned_data['playlist']
        for playlist in playlists:
            songs = playlist.songs.all()
            for song in songs:
                song.delete()
            playlist.delete()
            return redirect(self.success_url)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, *, object_list=None, **kwargs):  
        context = super().get_context_data(**kwargs)
        playlists = Playlist.objects.filter(user=self.request.user)
        context['playlists'] = playlists
        return context


class Playlist_Song(DetailView):
    model = Playlist
    template_name = 'main/song_list.html'
    context_object_name = 'songs'
    pk_url_kwarg = 'playlist_id'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        playlist = self.get_object()
        playlist_json = serializers.serialize('json', playlist.songs.all(), fields=('title', 'audio_file'))
        songs_with_index = {}
        for i, song in enumerate(playlist.songs.all()):
            songs_with_index[i] = song

        context['songs'] = songs_with_index
        context['playlist_json'] = playlist_json
        return context


class Song_CreateView(CreateView):
    model = Song
    template_name = 'main/add_song.html'
    form_class = SongForm
    success_url = reverse_lazy('song_list')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('register_client')
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        song = form.save(commit=False)
        song.user = self.request.user
        song.save()
        playlist_id = self.request.POST.get('playlist')
        playlist = Playlist.objects.get(id=playlist_id)
        playlist.songs.add(song)
        return redirect(self.success_url)

    def get_context_data(self, *, object_list=None, **kwargs): 
        context = super().get_context_data(**kwargs)
        playlists = Playlist.objects.filter(user=self.request.user)
        context['playlists'] = playlists
        return context


class DeleteSongsView(FormView):
    template_name = 'main/delete_song.html'
    form_class = DeleteSongForm
    success_url = reverse_lazy('song_list')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('register_client')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        songs = form.cleaned_data['songs']
        for song in songs:
            playlists = song.playlists.all()
            for playlist in playlists:
                playlist.songs.remove(song)
            song.delete()
        return redirect(self.success_url)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        songs = Song.objects.filter(user=self.request.user)
        context['songs'] = songs
        return context


class Song_ListView(ListView):
    template_name = 'main/song_list.html'
    context_object_name = 'songs'

    def dispatch(self, request, *args, **kwargs):  
        if not request.user.is_authenticated:
            return redirect('register_client')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self): 
        songs = Song.objects.filter(user_id=self.request.user.id)
        songs_with_index = {}
        for i, song in enumerate(songs):
            songs_with_index[i] = song
        return songs_with_index

    def get_context_data(self, *, object_list=None, **kwargs): 
        context = super().get_context_data(**kwargs)
        songs = Song.objects.filter(user_id=self.request.user.id)
        playlist_json = serializers.serialize('json', songs, fields=('title', 'audio_file'))
        context['playlist_json'] = playlist_json
        return context


class Key_ListView(ListView):
    template_name = 'main/key.html'
    context_object_name = 'songs'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('register_client')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self): 
        songs = Song.objects.filter(user_id=self.request.user.id)
        songs_with_index = {}
        for i, song in enumerate(songs):
            songs_with_index[i] = song
        return songs_with_index


def get_key(request):
    if request.method == 'POST':
        body_unicode = request.body.decode('utf-8')
        body_data = json.loads(body_unicode)
        file_path = body_data.get('file_path')
        key_, mode = Detector.get_key('.'+file_path)
        key_ = str(key_)
        mode = str(mode)
        print(key_, mode)
        return JsonResponse({'key': key_, 'mode': mode})
    return JsonResponse({'error': 'Invalid request method'})


class BPM_ListView(ListView):
    template_name = 'main/bpm.html'
    context_object_name = 'songs'

    def dispatch(self, request, *args, **kwargs):  
        if not request.user.is_authenticated:
            return redirect('register_client')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):  
        songs = Song.objects.filter(user_id=self.request.user.id)
        songs_with_index = {}
        for i, song in enumerate(songs):
            songs_with_index[i] = song
        return songs_with_index


def get_bpm(request):
    if request.method == 'POST':
        body_unicode = request.body.decode('utf-8')
        body_data = json.loads(body_unicode)
        file_path = body_data.get('file_path')
        bpm_ = Detector.get_tempo('.'+file_path)
        return JsonResponse({'bpm': bpm_})
    return JsonResponse({'error': 'Invalid request method'})

music_service/main/templates/main/add_playlist.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/form.css' %}">
{% endblock %}

{% block content %}
    <section class="login">
        <div class="form-box">
            <div class="form-value">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="inputbox">
                        <input type="text" id="id_title" name="title" required>
                        <label>Title</label>
                    </div>

                    <div class="inputbox file-input">
                        <label for="id_image" id="fileLabelImage">Choose File</label>
                        <input type="file" id="id_image" name="image" accept=".jpg,.png" required
                               onchange="updateFileLabel(this, 'fileLabelImage')">
                    </div>


                    <input type="submit" value="Create">
                </form>
            </div>
        </div>
    </section>

    <script>
        function updateFileLabel(input, labelId) {
            const label = document.getElementById(labelId);

            if (input.files.length > 0) {
                label.textContent = input.files[0].name;
            } else {
                label.textContent = 'Choose File';
            }
        }
    </script>
{% endblock %}

music_service/main/templates/main/add_song.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/form.css' %}">
{% endblock %}

{% block content %}
    <section class="login">
        <div class="form-box">
            <div class="form-value">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="inputbox">
                        <input type="text" id="id_title" name="title" required>
                        <label>Title</label>
                    </div>
                    <div class="inputbox file-input">
                        <label for="id_image" id="fileLabelAudio">Choose File</label>
                        <input type="file" id="id_audio_file" name="audio_file" accept=".mp3,.wav" required
                               onchange="updateFileLabel(this, 'fileLabelAudio')">
                    </div>

                    <div class="inputbox file-input">
                        <label for="id_image" id="fileLabelImage">Choose File</label>
                        <input type="file" id="id_image" name="image" accept=".jpg,.png" required
                               onchange="updateFileLabel(this, 'fileLabelImage')">
                    </div>

                    <div class="inputbox file-input">
                        <label for="id_image" id="fileLabelPlaylist">Choose Playlist</label>
                              <select id="id_playlist" name="playlist" onchange="updateFileLabel(this, 'fileLabelPlaylist')">
                        {% for playlist in playlists %}
                            <option value="{{ playlist.id }}">{{ playlist.title }}</option>
                        {% endfor %}
                    </select>
                    </div>

                    <input type="submit" value="Create">
                </form>
            </div>
        </div>
    </section>

    <script>
        function updateFileLabel(input, labelId) {
            const label = document.getElementById(labelId);

            if (input.files.length > 0) {
                label.textContent = input.files[0].name;
            } else {
                label.textContent = 'Choose File';
            }
        }
    </script>
{% endblock %}

music_service/main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Music store</title>
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            var contentMiddle = $('div.content__middle');

            if (contentMiddle[0].scrollHeight > contentMiddle.innerHeight()) {
                contentMiddle.addClass('scrollable');
            }

            $(window).resize(function () {
                if (contentMiddle[0].scrollHeight > contentMiddle.innerHeight()) {
                    contentMiddle.addClass('scrollable');
                } else {
                    contentMiddle.removeClass('scrollable');
                }
            });
        });
    </script>
    {% block head %}
    {% endblock %}
</head>
<body>

<div class="content__header">
    <div class="title">
        <a class="autorization-button" href="{% url 'home' %}">Music store</a>
    </div>
    <div class="current-track">
        {% block current-track %}
        {% endblock %}
    </div>
    <nav class="autorization">
        <div>
            {% if request.user.is_authenticated %}
            <p>
                <label class="autorization-button">{{ user.username }}</label>
                <a class="autorization-button" href="{% url 'logout' %}">Logout</a>
            </p>
            {% else %}
            <p>
                <a class="autorization-button" href="{% url 'login' %}">Login</a>
                <a class="autorization-button" href="{% url 'register_client' %}">Register</a>
            </p>
        </div>
        {% endif %}
    </nav>
</div>

<div class="container">

    <div class="content__left">

        <section class="navigation">

            <div class="navigation__list">

                <div class="navigation__list__header">
                    Function
                </div>

                <div class="collapse in" id="function">

                    <a href="{% url 'key' %}" class="navigation__list__item">
                        <span>Key</span>
                    </a>

                    <a href="{% url 'bpm' %}" class="navigation__list__item">
                        <span>BPM</span>
                    </a>
                </div>
            </div>

            <div class="navigation__list">

                <div class="navigation__list__header">
                    Your Music
                </div>

                <div class="collapse in" id="yourMusic">

                    <a href="{% url 'song_list' %}" class="navigation__list__item">
                        <span>Songs</span>
                    </a>

                    <a href="{% url 'playlists' %}" class="navigation__list__item">
                        <span>Playlists</span>
                    </a>

                </div>
            </div>
        </section>
        <div class="addController">
            {% block navigation_add %}
            {% endblock %}
            <a href="{% url 'add_song' %}" class="navigation__list__item ">
                <span>Add Song</span>
            </a>
            <a href="{% url 'add_playlist' %}" class="navigation__list__item ">
                <span>Add Playlist</span>
            </a>
            <a href="{% url 'delete_song' %}" class="navigation__list__item ">
                <span>Delete Song</span>
            </a>
            <a href="{% url 'delete_playlist' %}" class="navigation__list__item ">
                <span>Delete Playlist</span>
            </a>
        </div>
    </div>

    <div class="content__middle">
        {% block content %}
        {% endblock %}
    </div>
</div>

</body>
</html>

music_service/main/templates/main/bpm.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'main/css/song_list.css' %}">
{% endblock %}

{% block content %}
<div class="artist__content">
    <h1> Определение темпа песни</h1>
    <div class="mediaCards">
        <audio id="audioPlayer" controls style="display: none;" ontimeupdate="updateProgressBar()"></audio>
        {% for key, value in songs.items %}
        <div class="mediaCard" data-filepath="{{ value.audio_file.url}}">
            <img class="mediaCardImage" src="{{ value.image.url }}" alt="{{ song.title }}">
            <a class="mediaCardFooter">{{ value.title }}
                <span class="resultBPM">   </span>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<script>
    function determineKeyAndMode(filePath, card) {
        fetch('/key/get_bpm/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: JSON.stringify({file_path: filePath})
        })
            .then(response => response.json())
            .then(data => {
                const bpm = data.bpm;
                const resultKeyElement = card.querySelector('.resultBPM');
                resultKeyElement.textContent = 'bpm: ' + bpm;
            })
            .catch(error => {
                console.error('Error:', error);
            });
    }

    document.addEventListener('DOMContentLoaded', function () {
        const mediaCards = document.querySelectorAll('.mediaCard');

        mediaCards.forEach(function (card) {
            card.addEventListener('click', function () {
                const filePath = card.getAttribute('data-filepath');
                determineKeyAndMode(filePath, card);
            });
        });
    });

</script>
{% endblock %}

music_service/main/templates/main/delete_playlist.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/form.css' %}">
{% endblock %}

{% block content %}
    <section class="login">
        <div class="form-box">
            <div class="form-value">
                <form method="post">
                    {% csrf_token %}
                    <div class="inputbox file-input">
                        <select id="is_playlist" name="playlist">
                            {% for playlist in playlists %}
                                <option value="{{ playlist.id }}">{{ playlist.title }}</option>
                            {% endfor %}
                        </select>
                        <label>Select Playlist</label>
                    </div>
                <input type="submit" value="Delete Playlist">
                                </form>
            </div>
        </div>
    </section>
{% endblock %}

music_service/main/templates/main/delete_song.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/form.css' %}">
{% endblock %}

{% block content %}
    <section class="login">
        <div class="form-box">
            <div class="form-value">
                <form method="post">
                    {% csrf_token %}

                    <div class="inputbox file-input">
                        <select id="id_songs" name="songs">
                            {% for song in songs %}
                                <option value="{{ song.id }}">{{ song.title }}</option>
                            {% endfor %}
                        </select>
                        <label>Select Song</label>
                    </div>
                    <input type="submit" value="Delete Song">
                </form>
            </div>
        </div>
    </section>
    </form>

{% endblock %}

music_service/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block content %}



{% endblock %}

music_service/main/templates/main/key.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/song_list.css' %}">
{% endblock %}

{% block content %}
    <div class="artist__content">
        <h1> Определение тональности песни</h1>
        <div class="mediaCards">
            <audio id="audioPlayer" controls style="display: none;" ontimeupdate="updateProgressBar()"></audio>
            {% for key, value in songs.items %}
                <div class="mediaCard" data-filepath="{{ value.audio_file.url }}">
                    <img class="mediaCardImage" src="{{ value.image.url }}" alt="{{ song.title }}">
                    <a class="mediaCardFooter">{{ value.title }}
                        <span class="resultKey">   </span>
                        <span class="resultMode">   </span>

                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <script>
        function determineKeyAndMode(filePath, card) {
            fetch('/key/get_key/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify({file_path: filePath})
            })
                .then(response => response.json())
                .then(data => {
                    const key = data.key;
                    const mode = data.mode;
                    const resultKeyElement = card.querySelector('.resultKey');
                    const resultModeElement = card.querySelector('.resultMode');
                    resultKeyElement.textContent = 'Key: ' + key;
                    resultModeElement.textContent = mode;
                })
                .catch(error => {
                    console.error('Error:', error);
                });
        }

        document.addEventListener('DOMContentLoaded', function () {
            const mediaCards = document.querySelectorAll('.mediaCard');

            mediaCards.forEach(function (card) {
                card.addEventListener('click', function () {
                    const filePath = card.getAttribute('data-filepath');
                    determineKeyAndMode(filePath, card);
                });
            });
        });

    </script>
{% endblock %}

music_service/main/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/form.css' %}">
{% endblock %}

{% block content %}
    <section class="login">
        <div class="form-box">
            <div class="form-value">
                <h2>Login</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="inputbox">
                        {{ form.username }}
                        <label>Login</label>
                    </div>
                    <div class="inputbox">
                        {{ form.password }}
                        <label>Password</label>
                    </div>
                    <input type="submit" value="Log in">
                </form>
                <div class="register">
                    <p>Don't have a account <a href="{% url 'register_client' %}">Register</a></p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

music_service/main/templates/main/playlists.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'main/css/song_list.css' %}">
{% endblock %}


{% block content %}
    <div class="artist__content">
        <div class="mediaCards">
            {% for playlist in playlists %}
                <div class="mediaCard">
                    <a  href="{% url 'playlist_songs' playlist.id %}">
                        <img class="mediaCardImage" src="{{ playlist.image.url }}" alt="{{ playlist.title }}">
                        <a class="mediaCardFooter">{{ playlist.title }}</a>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

music_service/main/templates/main/register.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'main/css/form.css' %}">
{% endblock %}

{% block content %}
 <section class="login">
        <div class="form-box">
            <div class="form-value">
                <h2>Registration</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="inputbox">
                        {{ form.username }}
                        <label>Login</label>
                    </div>
                    <div class="inputbox">
                        {{ form.password }}
                        <label>Password</label>
                    </div>
                    <input type="submit" value="Register">
                </form>
                <div class="register">
                    <p>Have a account <a href="{% url 'login' %}"> Login</a></p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}